import { SidebarInset } from "@/components/ui/sidebar";
import { AppSidebar } from "@/app/(dashboard)/components/app-sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/toaster";
import { Metadata } from "next";
// import HoverDevCards from "@/components/dock";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function DashboardLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <AppSidebar />
      <SidebarInset>
        <div className="flex flex-col">
          <main className="flex flex-1 flex-col gap-4 p-4 pt-4 justify-center">
            {children}
          </main>
        </div>
      </SidebarInset>
      <Toaster />
    </SidebarProvider>
  );
}
