import Link from "next/link"
import { Calendar } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"

export default function TermsOfService() {
  return (
    <div className="space-y-8">
      {/* Title Section */}
      <div className="text-center space-y-4">
        <Badge variant="outline" className="mb-4">
          Legal
        </Badge>
        <h1 className="text-4xl md:text-5xl font-bold tracking-tight">Terms of Service</h1>
        <div className="flex items-center justify-center gap-2 text-muted-foreground">
          <Calendar className="h-4 w-4" />
          <span>Last Updated: July 19, 2025</span>
        </div>
      </div>

      {/* Introduction */}
      <div className="prose prose-lg max-w-none">
        <p className="text-lg text-muted-foreground leading-relaxed">
          Welcome to ngumpul.in! These Terms of Service ("Terms") govern your use of our website and services. By
          accessing or using ngumpul.in, you agree to be bound by these Terms.
        </p>
      </div>

      {/* Terms Content */}
      <div className="space-y-12">
        {/* Section 1 */}
        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-gray-900">1. Description of Service</h2>
          <div className="prose max-w-none">
            <p>
              Ngumpul.in is a platform designed to assist educators by streamlining the process of collecting,
              evaluating, and providing feedback on student assignments. Our key features include:
            </p>
            <ul className="space-y-2 mt-4">
              <li>
                <strong>Agentic AI Feedback & Correction:</strong> Automated analysis and feedback on student
                submissions, with communication styles that can be customized by the educator.
              </li>
              <li>
                <strong>Assignment Plagiarism Detection:</strong> A dynamic plagiarism score generated by comparing new
                submissions with previous assignments within the same folder.
              </li>
              <li>
                <strong>Student Clustering by Assignment Quality:</strong> Automatic grouping of student work based on
                metrics such as sentence count, page length, submission time, and plagiarism score.
              </li>
            </ul>
          </div>
        </section>

        {/* Section 2 */}
        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-gray-900">2. User Accounts</h2>
          <div className="prose max-w-none">
            <p>To access most features of ngumpul.in, you must register for an account. You agree to:</p>
            <ol className="space-y-2 mt-4">
              <li>Provide accurate, current, and complete information during the registration process.</li>
              <li>
                Maintain the security of your password and accept all risks of unauthorized access to your account.
              </li>
              <li>
                Promptly notify us if you discover or otherwise suspect any security breaches related to the service.
              </li>
            </ol>
          </div>
        </section>

        {/* Section 3 */}
        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-gray-900">3. User Responsibilities</h2>
          <div className="prose max-w-none">
            <p>
              You are solely responsible for your conduct and any data, text, files, information, and other content
              ("Content") that you submit, post, and display on the ngumpul.in service.
            </p>
            <p>You agree not to:</p>
            <ul className="space-y-2 mt-4">
              <li>Use the service for any illegal or unauthorized purpose.</li>
              <li>Infringe upon the intellectual property rights of others.</li>
              <li>Submit any Content that is unlawful, harmful, threatening, abusive, or otherwise objectionable.</li>
            </ul>
            <p className="mt-4">
              Educators and institutions are responsible for ensuring that their use of ngumpul.in complies with all
              applicable educational and data privacy laws, including obtaining any necessary consent from students for
              the processing of their work.
            </p>
          </div>
        </section>

        {/* Section 4 */}
        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-gray-900">4. Intellectual Property</h2>
          <div className="prose max-w-none">
            <p>
              <strong>Your Content:</strong> You retain all rights to the Content you submit to ngumpul.in. By using our
              service, you grant us a limited license to use, modify, reproduce, and distribute your Content solely for
              the purpose of operating and providing the service.
            </p>
            <p>
              <strong>Our Service:</strong> We and our licensors own all right, title, and interest in and to the
              ngumpul.in service, including all associated intellectual property rights.
            </p>
          </div>
        </section>

        {/* Section 5 */}
        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-gray-900">5. Disclaimers</h2>
          <div className="prose max-w-none">
            <p>
              The services, including the AI-generated feedback and plagiarism scores, are provided on an "as is" and
              "as available" basis. While we strive for accuracy, ngumpul.in does not guarantee that the feedback will
              be error-free or that the plagiarism detection will be 100% accurate. The tools provided are intended to
              be a support for educators, not a substitute for their professional judgment.
            </p>
          </div>
        </section>

        {/* Section 6 */}
        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-gray-900">6. Limitation of Liability</h2>
          <div className="prose max-w-none">
            <p>
              To the fullest extent permitted by applicable law, ngumpul.in shall not be liable for any indirect,
              incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether
              incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting
              from (a) your access to or use of or inability to access or use the service; (b) any conduct or content of
              any third party on the service.
            </p>
          </div>
        </section>

        {/* Section 7 */}
        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-gray-900">7. Termination</h2>
          <div className="prose max-w-none">
            <p>
              We may terminate or suspend your access to our service immediately, without prior notice or liability, for
              any reason whatsoever, including without limitation if you breach the Terms.
            </p>
          </div>
        </section>

        {/* Section 8 */}
        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-gray-900">8. Governing Law</h2>
          <div className="prose max-w-none">
            <p>
              These Terms shall be governed and construed in accordance with the laws of Indonesia, without regard to
              its conflict of law provisions.
            </p>
          </div>
        </section>

        {/* Section 9 */}
        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-gray-900">9. Changes to Terms</h2>
          <div className="prose max-w-none">
            <p>
              We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will
              provide at least 30 days' notice before any new terms take effect.
            </p>
          </div>
        </section>
      </div>

      {/* Footer CTA */}
      <div className="mt-16 p-8 bg-blue-50 rounded-lg text-center space-y-4">
        <h3 className="text-xl font-semibold">Questions about our Terms?</h3>
        <p className="text-muted-foreground">
          If you have any questions about these Terms of Service, please contact us.
        </p>
        <Button asChild>
          <Link href="/contact">Contact Us</Link>
        </Button>
      </div>
    </div>
  )
}
