import "@/styles/globals.css";
import { Gabarito } from "next/font/google"; // Impor font Gabarito
import { type Metadata } from "next";
import { Providers } from "./providers";
import { ClerkProvider } from "@clerk/nextjs";

// Konfigurasi font Gabarito
const gabarito = Gabarito({
  weight: "400", // Regular
  subsets: ["latin"], // Subset yang digunakan
  variable: "--font-gabarito", // Variabel CSS untuk font
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    // <ClerkProvider>
      <html
        lang="en"
        className={`${gabarito.variable}`} // Terapkan font Gabarito
        suppressHydrationWarning
      >
        <body>
          <Providers>{children}</Providers>
        </body>
      </html>
    // </ClerkProvider>
  );
}